=== Launching from a cloned Quick Start (recommended for production)

The fastest way to use the {partner-product-name-short} Quick Start is to launch it directly from its Amazon S3 bucket. However, when you do, any updates we make to the Quick Start templates will propagate directly to your deployment. These updates sometimes involve adding or removing parameters, which could introduce unexpected (and possibly breaking) changes to your deployment.

As such, or production environments, we recommend that you launch the {partner-product-name-short} Quick Start templates from a custom S3 bucket. Then, launch them directly from there. Launching from your own cloned Quick Start lets you control when to apply our latest changes to your environment.

include::./_clone_quickstart.adoc[]

Once you’ve uploaded everything, you’re ready to deploy your production stack from your S3 bucket. Go to *CloudFormation* > *Create Stack*. When specifying a template, paste in the Object URL of the Quick Start template you’ll be using. Choose *Next* to start configuring your deployment.

On the *Specify stack* details page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. For details about each setting, refer to the section matching your deployment type:

- <<launch-into-a-new-vpc>> (if you're deploying an ASI with {partner-product-name})
- <<launch-into-an-existing-vpc>> (if you're deploying {partner-product-name} into a new ASI)
